"""Two fixed answers through the real worker, pipeline and memory API readback.

No external model or place service, PostgreSQL or real account save is used.
The public response is generated by the current backend, never hand-written.
"""
import asyncio
import json

from app.trip_understanding.experience_inference import ExperienceQwenProvider
from app.trip_understanding.pipeline import TripUnderstandingPipeline
from app.trip_understanding.worker import TripUnderstandingWorker
from tests.semantic_page_replays import FixedReplayPlaces
from tests.test_semantic_supplement_budget import Client
from tests.test_trip_understanding_v3_api import _client


SOURCE = (
    '北京两日游。\nDay1：午餐在南门涮肉。之后去故宫博物院，午门进、神武门出，'
    '园内太和殿、乾清宫均要参观，实际先看乾清宫再看太和殿；时间充裕看珍宝馆。'
    '随后去景山公园，仅看外观，不进入内部。\n'
    'Day2：再访故宫博物院，只在门外取寄存的行李，不进展厅。之后去天坛公园，南门进北门出。'
)
FIRST = {'destination': '北京', 'day_labels': ['Day1', 'Day2'], 'activities': [
    {'source_quote': name, 'place_name': name, 'occurrence': occurrence, 'day_index': day,
     'role': 'PLANNED', 'category': category, 'city': '北京', 'city_evidence': '北京两日游'}
    for name, day, occurrence, category in [
        ('南门涮肉', 1, 1, '餐饮'), ('故宫博物院', 1, 1, '景点'), ('景山公园', 1, 1, '景点'),
        ('故宫博物院', 2, 2, '景点'), ('天坛公园', 2, 1, '景点')]
]}


def row(parent, kind, quote, evidence, *, occurrence=1, optional=False):
    return dict(parent_index=parent, kind=kind, source_quote=quote, evidence=evidence,
                occurrence=occurrence, optional=optional)


SECOND = {'city_fields': [], 'source_visits': [
    # The response puts EXIT first. Public instructions still put the gate
    # last, preserving the explicitly supplied inner execution order.
    row(0, 'EXIT', '神武门', '午门进、神武门出'),
    row(0, 'VISIT', '乾清宫', '园内太和殿、乾清宫均要参观'),
    row(0, 'VISIT', '太和殿', '园内太和殿、乾清宫均要参观'),
    row(0, 'VISIT', '珍宝馆', '时间充裕看珍宝馆', optional=True),
    row(0, 'ENTRY', '午门', '午门进、神武门出'),
    row(1, 'EXTERIOR_ONLY', '景山公园', '仅看外观，不进入内部'),
    row(2, 'PICKUP_ONLY', '故宫博物院', '只在门外取寄存的行李，不进展厅', occurrence=2),
    # occurrence=1 points inside the earlier restaurant 南门涮肉. This gate
    # must remain unresolved, while its valid sibling 北门 survives.
    row(3, 'ENTRY', '南门', '南门进北门出'),
    row(3, 'EXIT', '北门', '南门进北门出'),
]}


async def source_visit_page_replay():
    class CountedPlaces(FixedReplayPlaces):
        def __init__(self):
            self.calls = []

        async def resolve(self, **query):
            self.calls.append(query['atomic_place_name'])
            return await super().resolve(**query)

    model = Client(FIRST, SECOND)
    inference = ExperienceQwenProvider(api_key='test-only', base_url='https://test.invalid',
        model='controlled-two-answer', client=model, deadline_seconds=60,
        enable_source_visits=True)
    places = CountedPlaces()
    pipeline = TripUnderstandingPipeline(inference, places)
    client, repository, _app = _client()
    created = client.post('/api/v3/trip-understandings', headers={'Idempotency-Key': 'source-visits-page'},
        json={'mode': 'FULL', 'source': {'type': 'TEXT', 'text': SOURCE}})
    assert created.status_code == 202
    await TripUnderstandingWorker(repository, full_pipeline=pipeline).run_once('source-visits-page')
    first = client.get(created.json()['result_url'])
    readback = client.get(created.json()['result_url'])
    assert first.status_code == readback.status_code == 200
    assert first.json() == readback.json() and first.headers['etag'] == readback.headers['etag']
    assert len(model.calls) == 2
    assert set(places.calls) == {'南门涮肉', '故宫博物院', '景山公园', '天坛公园'}
    assert len(places.calls) <= 5
    request = json.loads(model.calls[1]['messages'][1]['content'])
    assert [parent['name'] for parent in request['parents']] == [
        '故宫博物院', '景山公园', '故宫博物院', '天坛公园']
    result = readback.json()
    assert [[card['name'] for card in day['activities']] for day in result['days']] == [
        ['南门涮肉', '故宫博物院', '景山公园'], ['故宫博物院', '天坛公园']]
    assert [item['name'] for item in result['days'][0]['activities'][1]['source_details']] == [
        '入口：午门', '乾清宫', '太和殿', '珍宝馆', '出口：神武门']
    assert [item['name'] for item in result['days'][0]['activities'][2]['source_details']] == ['仅看外观，不入内部']
    assert [item['name'] for item in result['days'][1]['activities'][0]['source_details']] == ['仅取物，不参观']
    assert [item['name'] for item in result['days'][1]['activities'][1]['source_details']] == ['出口：北门']
    assert result['coverage']['complete'] is False
    assert [day['unprocessed_count'] for day in result['days']] == [0, 1]
    for field in ('parent_index', 'detail_kind', 'parent_mention_id', 'role_evidence', 'SOURCE_VISIT_UNRESOLVED'):
        assert field not in json.dumps(result)
    client.close()
    return {'result': result, 'model_calls': len(model.calls), 'fixed_place_queries': places.calls,
            'readback': 'MEMORY_API_PERSISTED_AND_REREAD',
            'external_calls': 0, 'postgres_and_real_account_save': 'NOT_RUN'}


if __name__ == '__main__':
    print(json.dumps(asyncio.run(source_visit_page_replay()), ensure_ascii=False))
