const {test,expect}=require('@playwright/test')
const {randomUUID}=require('node:crypto')

const pageErrors=new WeakMap()
test.beforeEach(async({page})=>{
 pageErrors.set(page,[])
 page.on('pageerror',e=>pageErrors.get(page).push(e.name+': '+e.message.replace(/https?:\/\/\S+/g,'[url]')))
})
test.afterEach(async({page})=>{expect(pageErrors.get(page)).toEqual([])})

async function register(page,nickname) {
 await page.getByRole('button',{name:'注册账号',exact:true}).click()
 await page.getByLabel('邮箱',{exact:true}).fill(`release-${randomUUID()}@example.test`)
 await page.getByLabel('密码',{exact:true}).fill(`Test${randomUUID()}9`)
 await page.getByLabel('称呼（选填）',{exact:true}).fill(nickname)
 await page.getByRole('button',{name:'注册并继续',exact:true}).click()
}

test('real release: anonymous text, place edit, manual routes, PNG, account, share and private deletion',async({page,browser},info)=>{
 let routes=0
 page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname.endsWith('/map-renders'))routes++})
 await page.goto('/')
 await page.getByTestId('trip-source-text').fill('北京两日游。Day 1：故宫博物院 → 景山公园。Day 2：天坛公园 → 前门大街。')
 await page.getByTestId('create-full-trip').click()
 await expect(page.getByTestId('itinerary-workspace')).toBeVisible({timeout:120000})
 await expect(page.getByTestId('activity-card')).toHaveCount(4)
 await page.getByTestId('activity-card').first().getByRole('heading').click()
 const edit=page.getByTestId('pending-place-dropdown')
 await edit.getByRole('textbox').fill('北海公园')
 await edit.getByRole('button',{name:'搜索',exact:true}).click()
 const option=edit.locator('.pending-place-option').filter({hasText:'北海公园'}).first()
 await option.click({timeout:30000})
 await option.click()
 await expect(edit).toHaveCount(0,{timeout:30000})
 expect(routes).toBe(0)
 await page.reload()
 await expect(page.getByTestId('activity-card').first()).toContainText('北海公园',{timeout:30000})
 await page.getByTestId('desktop-nav-map_stay').click()
 await expect(page.getByTestId('render-map')).toBeEnabled()
 await page.getByTestId('render-map').click()
 await expect.poll(()=>routes).toBe(1)
 await expect(page.getByTestId('map-theater')).toHaveAttribute('data-map-status',/^(AVAILABLE|LIMITED)$/,{timeout:90000})
 await expect(page.getByTestId('route-map')).toBeVisible()
 await expect.poll(()=>page.locator('.e-map-marker').count(),{timeout:30000}).toBeGreaterThan(0)
 await page.screenshot({path:info.outputPath('live-map.png'),fullPage:true})
 await page.getByTestId('desktop-nav-itinerary').click()
 await page.getByRole('button',{name:'导出图片',exact:true}).click()
 await expect(page.getByTestId('download-itinerary-png')).toBeVisible()
 const download=page.waitForEvent('download')
 await page.getByTestId('download-itinerary-png').click()
 const png=await download
 expect(png.suggestedFilename()).toMatch(/\.png$/)
 expect(await png.failure()).toBeNull()
 await png.saveAs(info.outputPath('complete-trip.png'))
 await page.getByLabel('关闭图片预览').click()
 await page.getByRole('button',{name:'保存到账号',exact:true}).click()
 await expect(page).toHaveURL(/\/login$/)
 await register(page,'首版流程测试')
 await expect(page.getByRole('button',{name:'已保存到账号',exact:true})).toBeVisible({timeout:30000})
 await page.reload()
 await expect(page.getByRole('button',{name:'已保存到账号',exact:true})).toBeVisible({timeout:30000})
 await page.getByLabel('更多行程操作').click()
 await page.getByTestId('share-trip').click()
 const share=page.getByLabel('分享链接',{exact:true})
 await expect(share).toBeVisible({timeout:30000})
 const shareUrl=await share.inputValue()
 const visitor=await browser.newContext()
 try {
  const shared=await visitor.newPage()
  await shared.goto(shareUrl)
  await expect(shared.getByText('北海公园',{exact:false}).first()).toBeVisible({timeout:30000})
  await expect(shared.getByTestId('pending-place-dropdown')).toHaveCount(0)
 } finally {await visitor.close()}
 await page.keyboard.press('Escape')
 await page.getByLabel('更多行程操作').click()
 await page.getByTestId('delete-trip-source').click()
 await page.getByRole('button',{name:'确认永久删除',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0,{timeout:30000})
 await expect(page.getByTestId('activity-card')).toHaveCount(4)
 await page.getByLabel('更多行程操作').click()
 await page.getByTestId('delete-entire-trip').click()
 await page.getByRole('button',{name:'确认永久删除',exact:true}).click()
 await expect(page.getByTestId('activity-card')).toHaveCount(0,{timeout:30000})
 expect(routes).toBe(1)
})

test('real collaboration: two accounts join, AI places synchronize, explicit driving, save and transfer',async({page,browser},info)=>{
 let optimization=0
 page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname.endsWith('/optimize'))optimization++})
 await page.goto('/collaborate')
 await expect(page).toHaveURL(/\/login$/)
 await register(page,'协同测试甲')
 await expect(page).toHaveURL(/\/collaborate$/,{timeout:30000})
 await page.getByLabel('目的地（选填）').fill('北京')
 await page.getByLabel('行程天数').selectOption('1')
 await page.getByRole('button',{name:'创建协同房间',exact:true}).click()
 await expect(page).toHaveURL(/\/room\/[^/?#]+$/,{timeout:30000})
 const roomUrl=page.url(),roomId=new URL(roomUrl).pathname.split('/').pop()
 await expect(page.getByTestId('chat-input')).toBeVisible()
 const second=await browser.newContext()
 try {
  const peer=await second.newPage()
  peer.on('pageerror',e=>pageErrors.get(page).push('peer: '+e.name))
  await peer.goto(new URL('/collaborate',roomUrl).href)
  await register(peer,'协同测试乙')
  await expect(peer.getByLabel('房间号')).toBeVisible({timeout:30000})
  await peer.getByLabel('房间号').fill(roomId)
  await peer.getByRole('button',{name:'加入协同房间',exact:true}).click()
  await expect(peer).toHaveURL(roomUrl,{timeout:30000})
  // Room's real initial AI request supplies provider-verified candidates.
  for(const tab of ['美景','美食','美梦']) {
   await page.getByRole('button',{name:new RegExp(tab)}).first().click()
   const choice=page.locator('[data-place-id]').filter({has:page.getByText(({'美景':'🏛 景点','美食':'🍜 美食','美梦':'🏨 住宿'})[tab],{exact:true})}).getByRole('button',{name:/^选择 /}).first()
   await expect.poll(async()=>await choice.count()>0||await page.getByText('暂时无法完成，请稍后重试。',{exact:true}).count()>0,{timeout:120000}).toBe(true)
   await expect(choice).toBeVisible()
   const selectedName=(await choice.getAttribute('aria-label')).replace(/^选择 /,'')
   await page.getByRole('button',{name:`选择 ${selectedName}`,exact:true}).click()
   await expect(page.getByRole('button',{name:`取消选择 ${selectedName}`,exact:true})).toBeVisible()
   console.log('Shared selection category:',tab)
   await peer.getByRole('button',{name:new RegExp(tab)}).first().click()
   await expect(peer.getByRole('button',{name:`取消选择 ${selectedName}`,exact:true})).toBeVisible({timeout:30000})
  }
  expect(optimization).toBe(0)
  const chat=page.getByTestId('chat-input')
  await chat.fill('这些地点中，第一次来北京可以优先选哪一处？请简短回答。')
  await expect(page.getByTestId('chat-send')).toBeEnabled({timeout:45000})
  const chatDone=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/chat'&&r.request().method()==='POST')
  await page.getByTestId('chat-send').click()
  const chatResponse=await chatDone
  expect(chatResponse.status()).toBe(200)
  await chat.fill('保留为未发送的草稿')
  await expect(page.getByTestId('chat-send')).toBeEnabled({timeout:45000})
  await expect(page.locator('.rounded-tl-md')).toHaveCount(2)
  await expect(page.locator('.rounded-tl-md').last()).not.toBeEmpty()
  await expect(page.getByText('暂时无法完成，请稍后重试。',{exact:true})).toHaveCount(0)
  await chat.clear()
  await page.getByRole('button',{name:/智能排线/}).click()
  await expect.poll(()=>optimization,{timeout:90000}).toBe(1)
  await expect(page.getByRole('button',{name:'转入行程查',exact:true})).toBeEnabled({timeout:120000})
  await page.screenshot({path:info.outputPath('collaboration-saved.png'),fullPage:true})
  await page.reload()
  await expect(page.getByRole('button',{name:'转入行程查',exact:true})).toBeEnabled({timeout:30000})
  expect(optimization).toBe(1)
  await page.getByRole('button',{name:'转入行程查',exact:true}).click()
  await expect(page.getByTestId('itinerary-workspace')).toBeVisible({timeout:120000})
  await expect(page.getByRole('button',{name:'已保存到账号',exact:true})).toBeVisible()
  expect(await page.getByTestId('activity-card').count()).toBeGreaterThan(0)
  await peer.reload()
  await expect(peer.getByTestId('chat-input')).toBeVisible({timeout:30000})
 } finally {await second.close()}
})

test('landmark ROI: real short names become main-place cards and manual search stays local',async({page},info)=>{
 let routes=0, edits=0
 page.on('request',r=>{if(r.method()==='POST'){const path=new URL(r.url()).pathname;if(path.endsWith('/commands'))edits++;if(path.endsWith('/map-renders'))routes++}})
 await page.goto('/')
 await page.getByTestId('trip-source-text').fill('北京两日游。Day 1：天安门广场 → 故宫 → 景山公园。Day 2：鸟巢 → 水立方 → 后海。')
 const start=Date.now()
 await page.getByTestId('create-full-trip').click()
 await expect(page.getByTestId('itinerary-workspace')).toBeVisible({timeout:120000})
 const cards=page.getByTestId('activity-card')
 await expect(cards).toHaveCount(6)
 const names=await cards.getByRole('heading').allTextContents()
 expect(names).toEqual(['天安门广场','故宫博物院','景山公园','国家体育场','国家游泳中心','后海'])
 for(const card of await cards.all()) await expect(card).toContainText('已确认')
 await info.attach('matching-summary',{body:JSON.stringify({cards:6,confirmed:6,generationMs:Date.now()-start,names}),contentType:'application/json'})
 await page.screenshot({path:info.outputPath('matched-landmarks.png'),fullPage:true})
 await cards.first().getByRole('heading').click()
 const edit=page.getByTestId('pending-place-dropdown')
 await edit.getByRole('textbox').fill('鸟巢')
 await edit.getByRole('button',{name:'搜索',exact:true}).click()
 const option=edit.locator('.pending-place-option').first()
 await expect(option).toContainText('国家体育场',{timeout:30000})
 await option.click()
 expect(edits).toBe(0)
 await option.click()
 await expect(edit).toHaveCount(0,{timeout:30000})
 await expect(cards.first()).toContainText('国家体育场')
 expect(edits).toBe(1);expect(routes).toBe(0)
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.getByTestId('desktop-nav-map_stay').click()
 await page.getByTestId('render-map').click()
 await expect.poll(()=>routes).toBe(1)
 await expect(page.getByTestId('map-theater')).toHaveAttribute('data-map-status',/^(AVAILABLE|LIMITED)$/,{timeout:90000})
 await page.screenshot({path:info.outputPath('matched-map.png'),fullPage:true})
})

test('landmark ROI: Shanghai short names resolve while unspecified museum remains a choice',async({page},info)=>{
 await page.goto('/')
 await page.getByTestId('trip-source-text').fill('上海两日游。Day 1：外滩 → 东方明珠。Day 2：武康路 → 上海博物馆。')
 await page.getByTestId('create-full-trip').click()
 await expect(page.getByTestId('itinerary-workspace')).toBeVisible({timeout:120000})
 const cards=page.getByTestId('activity-card')
 await expect(cards).toHaveCount(4)
 expect(await cards.getByRole('heading').allTextContents()).toEqual(['外滩','东方明珠广播电视塔','武康路','上海博物馆'])
 for(const index of [0,1,2]) await expect(cards.nth(index)).toContainText('已确认')
 await expect(cards.nth(3)).toContainText('待确认')
 await cards.nth(3).getByRole('heading').click()
 const edit=page.getByTestId('pending-place-dropdown')
 await edit.getByRole('textbox').fill('上海博物馆')
 await edit.getByRole('button',{name:'搜索',exact:true}).click()
 await expect(edit).toContainText('上海博物馆(人民广场馆)',{timeout:30000})
 await expect(edit).toContainText('上海博物馆(东馆)')
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.screenshot({path:info.outputPath('museum-choice.png'),fullPage:true})
})
