const {test,expect}=require('@playwright/test')
const backend='http://127.0.0.1:8185'
const control=async(request,body)=>(await request.post(`${backend}/__control`,{data:body})).json()
test.beforeEach(async({request})=>{await control(request,{action:'reset'})})

test('continuous snapshots preserve cards, reading, cursor and final focus',async({page,request})=>{
  await page.goto('/trip/result#trip=live-generation-cards-resource')
  await expect(page.getByText('实时接收中',{exact:true})).toBeVisible()
  expect((await control(request,{action:'advance',count:3,ready:0})).connections).toBe(1)
  const card=page.locator('[data-generation-token="controlled-visit-0"]')
  await expect(card).toHaveAttribute('data-state','checking')
  await card.getByRole('button').click()
  await control(request,{action:'advance',count:3,ready:2,detail:true})
  await expect(card).toHaveAttribute('data-state','ready')
  await expect(card.getByRole('button')).toHaveAttribute('aria-expanded','true')
  await expect(card).toContainText('太和殿')
  await control(request,{action:'advance',count:8,ready:5,detail:true})
  await expect(page.getByRole('button',{name:'新增 5 个地点，查看新增内容'})).toBeVisible()
  await expect(card.getByRole('button')).toBeFocused()
  await page.getByRole('button',{name:'新增 5 个地点，查看新增内容'}).click()
  const lastUpdate=await control(request,{action:'advance',count:12,ready:8,detail:true})
  await control(request,{action:'duplicate'})
  await expect(page.locator('[data-generation-token]')).toHaveCount(12)
  await expect(page.getByRole('button',{name:'景山公园 景点',exact:true})).toHaveCount(2)
  await control(request,{action:'disconnect'})
  await expect.poll(async()=> (await control(request,{})).requests.at(-1)).toBe(lastUpdate.cursor)
  await page.reload()
  await expect(page.locator('[data-generation-token]')).toHaveCount(12)
  await page.getByRole('button',{name:'Day 2 4 个地点',exact:true}).click()
  await page.getByRole('button',{name:'前门大街 景点',exact:true}).click()
  await control(request,{action:'advance',count:12,ready:12,detail:true})
  await control(request,{action:'finish'})
  await expect(page.getByTestId('generation-workspace')).toHaveCount(0)
  await expect(page.locator('[data-visit-id="controlled-visit-5"] .four-card-copy')).toBeFocused()
  await expect(page.getByRole('button',{name:'拖动 前门大街',exact:true})).toBeEnabled()
})

test('stop preserves confirmed cards and excludes unconfirmed cards from the mainline',async({page,request})=>{
  await page.goto('/trip/result#trip=live-generation-cards-resource')
  await expect(page.getByText('实时接收中',{exact:true})).toBeVisible()
  await control(request,{action:'advance',count:4,ready:1,detail:true})
  await expect(page.locator('[data-generation-token]')).toHaveCount(4)
  await page.getByRole('button',{name:'停止整理',exact:true}).click()
  await expect(page.getByRole('button',{name:'拖动 故宫博物院',exact:true})).toBeEnabled()
  await expect(page.getByRole('button',{name:'拖动 景山公园',exact:true})).toHaveCount(0)
  await expect(page.getByText('已取消：王府井',{exact:true})).toBeVisible()
})
